tables [
  'accounts',    'loans',
  'approvals',   'vouchers',
  'collections', 'changefunds',
  'banks',       'bankaccounts',
  'products',    'agents',
  'addresses',   'lookups'
]
# TABLE accounts 10 rows
INSERT INTO `accounts` (`bank`,`name`,`pension`,`pn`,`provider`,`status`,`type`) VALUES ('2012-7000-5585','Adela Buriel',8500,'MUCC-103-001','SSS','Active','Loan-70n');
INSERT INTO `accounts` (`bank`,`name`,`pension`,`pn`,`provider`,`status`,`type`) VALUES ('2012-7000-5585','Reynaldo Bascon',9200,'MUCC-103-002','SSS','Active','Loan-72n');
INSERT INTO `accounts` (`bank`,`name`,`pension`,`pn`,`provider`,`status`,`type`) VALUES ('2012-7000-5585','Zenaldo Clavio',10500,'MUCC-103-003','SSS','Active','Loan-75n');
INSERT INTO `accounts` (`bank`,`name`,`pension`,`pn`,`provider`,`status`,`type`) VALUES ('2012-7000-5585','Teodora Dionisio',11200,'MUCC-103-004','SSS','Active','Loan-79n');
INSERT INTO `accounts` (`bank`,`name`,`pension`,`pn`,`provider`,`status`,`type`) VALUES ('2012-7000-5585','Eduardo Laquindanum',12500,'MUCC-103-005','SSS','Active','Loan-80n');
INSERT INTO `accounts` (`bank`,`name`,`pension`,`pn`,`provider`,`status`,`type`) VALUES ('2012-7000-5585','Zenaida Dela Cruz',8500,'MUCC-103-006','SSS','Active','Loan-70x');
INSERT INTO `accounts` (`bank`,`name`,`pension`,`pn`,`provider`,`status`,`type`) VALUES ('2012-7000-5585','Thelma Dionisio',9200,'MUCC-103-007','SSS','Active','Loan-72x');
INSERT INTO `accounts` (`bank`,`name`,`pension`,`pn`,`provider`,`status`,`type`) VALUES ('2012-7000-5585','Hospicio Dulay',10500,'MUCC-103-008','SSS','Active','Loan-75x');
INSERT INTO `accounts` (`bank`,`name`,`pension`,`pn`,`provider`,`status`,`type`) VALUES ('2012-7000-5585','Mercedita Esguerra',11200,'MUCC-103-009','SSS','Active','Loan-79x');
INSERT INTO `accounts` (`bank`,`name`,`pension`,`pn`,`provider`,`status`,`type`) VALUES ('2012-7000-5585','Leticia Espiritu',12500,'MUCC-103-010','SSS','Active','Loan-80x');
# TABLE loans 5 rows
INSERT INTO `loans` (`amort`,`cashout`,`date`,`ins`,`interest`,`name`,`not`,`principal`,`proc`,`ref`,`status`,`terms`) VALUES (4200,39816,'2025-03-15',0,10080,'Julius Bolanos',0,50400,504,'A33L5QE866','Active',12);
INSERT INTO `loans` (`amort`,`cashout`,`date`,`ins`,`interest`,`name`,`not`,`principal`,`proc`,`ref`,`status`,`terms`) VALUES (3800,54036,'2025-04-22',0,13680,'Maria Santos',0,68400,684,'A92K4MX739','Active',18);
INSERT INTO `loans` (`amort`,`cashout`,`date`,`ins`,`interest`,`name`,`not`,`principal`,`proc`,`ref`,`status`,`terms`) VALUES (4500,85320,'2025-05-10',0,21600,'Roberto Cruz',0,108000,1080,'B47N8PQ215','Active',24);
INSERT INTO `loans` (`amort`,`cashout`,`date`,`ins`,`interest`,`name`,`not`,`principal`,`proc`,`ref`,`status`,`terms`) VALUES (5200,49296,'2025-06-05',0,12480,'Carmen Reyes',0,62400,624,'C15R3ST847','Active',12);
INSERT INTO `loans` (`amort`,`cashout`,`date`,`ins`,`interest`,`name`,`not`,`principal`,`proc`,`ref`,`status`,`terms`) VALUES (4800,68256,'2025-07-18',0,17280,'Fernando Lopez',0,86400,864,'D28M7VY963','Active',18);
# TABLE approvals 5 rows
INSERT INTO `approvals` (`amort`,`date`,`name`,`principal`,`ref`,`status`,`terms`) VALUES (3900,'2025-08-01','Lourdes Torres',46800,'A88L2ZE754','Pending',12);
INSERT INTO `approvals` (`amort`,`date`,`name`,`principal`,`ref`,`status`,`terms`) VALUES (4100,'2025-08-05','Eduardo Ramos',73800,'B55K9MX328','Pending',18);
INSERT INTO `approvals` (`amort`,`date`,`name`,`principal`,`ref`,`status`,`terms`) VALUES (4700,'2025-08-10','Gloria Hernandez',112800,'C33N7PQ441','Pending',24);
INSERT INTO `approvals` (`amort`,`date`,`name`,`principal`,`ref`,`status`,`terms`) VALUES (5100,'2025-08-12','Rodrigo Flores',61200,'D66M3VY855','Pending',12);
INSERT INTO `approvals` (`amort`,`date`,`name`,`principal`,`ref`,`status`,`terms`) VALUES (4300,'2025-08-15','Teresita Gutierrez',77400,'E77R4ST966','Pending',18);
# TABLE vouchers 15 rows
INSERT INTO `vouchers` (`acct`,`amount`,`date`,`no`,`payee`,`status`) VALUES ('2012-7000-5585',0,'2025-03-28','0000000010','Francisco Rivera','Active');
INSERT INTO `vouchers` (`acct`,`amount`,`date`,`no`,`payee`,`status`) VALUES ('2012-7000-5585',0,'2025-05-21','0000000011','Rodolfo Vistan','Active');
INSERT INTO `vouchers` (`acct`,`amount`,`date`,`no`,`payee`,`status`) VALUES ('2012-7000-5585',0,'2025-05-21','0000000012','Pablo Marquez','Active');
INSERT INTO `vouchers` (`acct`,`amount`,`date`,`no`,`payee`,`status`) VALUES ('2012-7000-5585',0,'2025-05-22','0000000013','Teodorica Delgado','Active');
INSERT INTO `vouchers` (`acct`,`amount`,`date`,`no`,`payee`,`status`) VALUES ('2012-7000-5585',0,'2025-05-26','0000000014','Gloria De Leon','Active');
INSERT INTO `vouchers` (`acct`,`amount`,`date`,`no`,`payee`,`status`) VALUES ('2012-7000-5585',0,'2025-05-26','0000000015','Olivia Santos','Active');
INSERT INTO `vouchers` (`acct`,`amount`,`date`,`no`,`payee`,`status`) VALUES ('2012-7000-5585',0,'2025-05-26','0000000016','Romulo Berey','Active');
INSERT INTO `vouchers` (`acct`,`amount`,`date`,`no`,`payee`,`status`) VALUES ('2012-7000-5585',20000,'2025-06-10','0000000017','KENNITH A. OCHOA','Active');
INSERT INTO `vouchers` (`acct`,`amount`,`date`,`no`,`payee`,`status`) VALUES ('2012-7000-5585',1615,'2025-06-10','0000000018','Virginia Clemente','Active');
INSERT INTO `vouchers` (`acct`,`amount`,`date`,`no`,`payee`,`status`) VALUES ('2012-7000-5585',4376,'2025-07-18','0000000019','Herminia Latoza','Active');
INSERT INTO `vouchers` (`acct`,`amount`,`date`,`no`,`payee`,`status`) VALUES ('2012-7000-5585',59350,'2025-10-13','0000000020','Patrick Delos Santos','Active');
INSERT INTO `vouchers` (`acct`,`amount`,`date`,`no`,`payee`,`status`) VALUES ('2012-7000-5585',20000,'2026-04-13','0000000021','KENNITH A. OCHOA','Active');
INSERT INTO `vouchers` (`acct`,`amount`,`date`,`no`,`payee`,`status`) VALUES ('2012-7000-5585',7447,'2026-04-27','0000000022','Rufina Bodino','Active');
INSERT INTO `vouchers` (`acct`,`amount`,`date`,`no`,`payee`,`status`) VALUES ('2012-7000-5585',10000,'2026-04-27','0000000023','JAISSA DUPLON','Active');
INSERT INTO `vouchers` (`acct`,`amount`,`date`,`no`,`payee`,`status`) VALUES ('2012-7000-5585',5000,'2026-04-27','0000000024','Elenita Hilario','Active');
# TABLE collections 30 rows
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (2800,0,'Adela Buriel','2011-10-10','0000300139','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (6000,0,'Reynaldo Bascon','2011-10-09','0000300193','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (12900,0,'Zenaldo Clavio','2011-10-26','0000300240','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (2300,0,'Teodora Dionisio','2011-10-17','0000300253','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (1000,0,'Eduardo Laquindanum','2011-09-18','0000300303','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (1000,0,'Eduardo Laquindanum','2011-10-17','0000300304','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (3200,0,'Zenaida Dela Cruz','2011-11-14','0000300357','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (12400,0,'Thelma Dionisio','2011-11-30','0000300360','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (6500,0,'Hospicio Dulay','2011-11-30','0000300362','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (2000,0,'Mercedita Esguerra','2011-11-03','0000300363','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (2000,0,'Mercedita Esguerra','2011-11-30','0000300364','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (1000,0,'Leticia Espiritu','2011-11-30','0000300369','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (3500,0,'Jorge Estrada','2011-10-10','0000300370','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (3500,0,'Jorge Estrada','2011-11-14','0000300371','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (7500,0,'Jorge Estrada','2011-11-30','0000300372','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (4000,0,'Julian Caparas','2011-10-03','0000300375','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (4000,0,'Julian Caparas','2011-11-02','0000300376','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (4000,0,'Julian Caparas','2011-11-30','0000300377','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (3800,0,'Bienvenido Francisco','2011-10-02','0000300381','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (5400,0,'Feliciana Pascual','2011-12-19','0000300390','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (1000,0,'Victoria Gatchalian','2011-12-06','0000300391','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (1000,0,'Victoria Gatchalian','2012-01-02','0000300392','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (2400,0,'Carmelita Llamas','2012-01-30','0000300393','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (5500,0,'Roberto Hernandez','2012-02-28','0000300394','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (3200,0,'Nora Villanueva','2012-03-31','0000300395','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (7800,0,'Ramon Gutierrez','2012-04-30','0000300396','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (1500,0,'Amelia Castillo','2012-05-31','0000300397','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (4200,0,'Domingo Reyes','2012-06-30','0000300398','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (6100,0,'Elena Santos','2012-07-31','0000300399','','Active');
INSERT INTO `collections` (`amount`,`bonus`,`cust`,`date`,`no`,`remarks`,`status`) VALUES (2900,0,'Pedro Cruz','2012-08-31','0000300400','','Active');
# TABLE changefunds 27 rows
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (2000,'Malolos','2025-02-06','Ma. Nery Bacani','0000000001','','Credit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (2000,'Malolos','2025-02-06','Ma. Nery Bacani','0000000002','Ref Collection#: 0000452775','Debit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (5000,'Malolos','2025-03-26','MARINO QUITELES','0000000003','','Credit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (200,'Malolos','2025-03-26','Leoncia Ganaden','0000000004','','Credit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (2400,'Malolos','2025-03-26','MARINO QUITELES','0000000005','Ref Collection#: 0000452776','Debit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (24000,'Malolos','2025-03-26','MARINO QUITELES','0000000006','','Credit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (500,'Malolos','2025-03-26','Fe Ablaza','0000000007','','Credit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (500,'Malolos','2025-03-26','Fe Ablaza','0000000008','Ref Collection#: 0000452777','Debit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (200,'Malolos','2025-03-26','Olivia Daria','0000000009','','Credit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (1000,'Malolos','2025-03-26','Rufina Bodino','0000000010','CF MAR (2025.03.26-POSBAL)','Credit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (500,'Malolos','2025-03-26','Fe Ablaza','0000000011','','Credit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (500,'Malolos','2025-03-26','Rufina Bodino','0000000012','SSS CF: MARCH','Credit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (400,'Malolos','2025-03-28','Ricardo Ablaza','0000000013','Ref Collection#: 0000452780','Debit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (400,'Malolos','2025-03-28','Ricardo Ablaza','0000000014','','Credit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (0,'Malolos','2025-05-22','Rufina Bodino','0000000015','','Credit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (5000,'Malolos','2025-10-13','Patrick Delos Santos','0000000016','lost coll. (OCT 2025)','Debit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (7000,'Malolos','2025-10-16','Patrick Delos Santos','0000000017','Ref Collection#: 0000452782','Debit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (7000,'Malolos','2025-10-16','Patrick Delos Santos','0000000018','','Debit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (200,'Malolos','2026-04-13','Reynaldo De Guzman','0000000019','Ref Collection#: 0000452784','Debit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (1000,'Malolos','2026-04-13','Eleuterio Reyes','0000000020','Ref Collection#: 0000452785','Debit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (1800,'Malolos','2026-04-13','Fe Ablaza','0000000021','Ref Collection#: 0000452786','Debit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (480,'Malolos','2026-04-13','Olivia Daria','0000000022','Ref Collection#: 0000452787','Debit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (4000,'Malolos','2026-04-13','Elenita Hilario','0000000023','Ref Collection#: 0000452788','Debit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (3500,'Malolos','2026-04-27','Ma. Nery Bacani','0000000024','','Credit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (2000,'Malolos','2026-04-27','Ricardo Ablaza','0000000025','Ref Collection#: 0000452789','Debit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (1200,'Malolos','2026-04-27','Leonora Gili','0000000026','','Credit');
INSERT INTO `changefunds` (`amount`,`branch`,`date`,`name`,`no`,`remarks`,`type`) VALUES (800,'Malolos','2026-04-27','Anita Clemente','0000000027','Ref Collection#: 0000452790','Debit');
# TABLE banks 25 rows
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Allied Bank','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Asia United Bank Corporation','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Bank of Commerce','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Bank of the Philippine Islands','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','BDO Unibank, Inc.','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','China Banking Corporation','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','CTBC Bank (Philippines) Corporation','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Development Bank of the Philippines','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','East West Banking Corp.','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Gateway Rural Bank, Inc.','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Land Bank of the Philippines','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Maybank Philippines, Inc.','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Metropolitan Bank and Trust Co.','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Overseas Filipino Bank','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Palawan Bank','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Philippine Bank of Communications','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Philippine Business Bank','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Philippine National Bank','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Philippine Savings Bank','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Philippine Trust Company','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Philippine Veterans Affairs Office','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Philippine Veterans Bank','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Security Bank Corp.','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','United Coconut Planters Bank','','');
INSERT INTO `banks` (`addr`,`contact`,`name`,`pos`,`tel`) VALUES ('','','Unionbank of the Philippines','','');
# TABLE bankaccounts 2 rows
INSERT INTO `bankaccounts` (`acctno`,`addr`,`bal`,`bank`) VALUES ('MB-1234','',0,'Metropolitan Bank and Trust Co.');
INSERT INTO `bankaccounts` (`acctno`,`addr`,`bal`,`bank`) VALUES ('2012-7000-5585','',0,'Philippine National Bank');
# TABLE products 30 rows
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Additional loan for Pensioners 70 years old and below','Loan-70a','Additional');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Additional loan for Pensioners 71 to 72 years old','Loan-72a','Additional');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Additional loan for Pensioners 73 to 75 years old','Loan-75a','Additional');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Additional loan for Pensioners 76 to 79 years old','Loan-79a','Additional');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Additional loan for Pensioners 80 and ABOVE','Loan-80a','Additional');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Bonus loan for SSS clients - August only','BONUS LOAN August','Bonus');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Bonus loan for SSS clients - July only','BONUS LOAN July','Bonus');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Bonus loan for SSS clients - November only','BONUS LOAN November','Bonus');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Bonus loan for SSS clients - October only','BONUS LOAN October','Bonus');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Bonus loan for SSS clients - September only','BONUS LOAN September','Bonus');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('For Agent Based Buy-out Clients','BUY-OUT 70n (AGENT BASED)','BUY OUT NEW');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('For prospective buy-out clients','BuyOut-70n - New and Below (WALK-IN)','BUY OUT NEW');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('For Agent Based Buy-out Clients','BUY-OUT 70r (AGENT BASED)','BUY OUT REN');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('For prospective buy-out clients','BuyOut-70r - Renewal and Below','BUY OUT REN');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Discounted Extension Loan from current date to date of ACOP/APIR','CORRECTIVE DISCOUNTED LOAN EXTENSION','CORRECTIVE DISCOUNT LOAN');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Client qualified for discounted renewal loan','CORRECTIVE DISCOUNTED LOAN RENEWAL','CORRECTIVE DISCOUNT LOAN');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Extension loan for Pensioners 70 years old and below','Loan 70x','Extension');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Extension loan for Pensioners 71 to 72 years old','Loan-72x','Extension');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Extension loan for Pensioners 73 to 75 years old','Loan-75x','Extension');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Extension loan for Pensioners 76 to 79 years old','Loan-79x','Extension');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Extension loan for Pensioners 80 years and ABOVE','Loan-80x and ABOVE','Extension');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('New loan for Pensioners 70 years old and below','Loan 70n','New');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('New loan for Pensioners 71 to 72 years old','Loan-72n','New');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('New loan for Pensioners 73 to 75 years old','Loan-75n','New');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('New loan for Pensioners 76 to 79 years old','Loan-79n','New');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('New loan for Pensioners 80 years and ABOVE','Loan-80n and ABOVE','New');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Renewal loan for Pensioners 70 years old and below','Loan 70r','Renewal');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Renewal loan for Pensioners 71 to 72 years old','Loan-72r','Renewal');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Renewal loan for Pensioners 73 to 75 years old','Loan-75r','Renewal');
INSERT INTO `products` (`desc`,`name`,`type`) VALUES ('Renewal loan for Pensioners 76 to 79 years old','Loan-79r','Renewal');
# TABLE agents 30 rows
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Lugam, Malolos','003','Ana Santos','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Lugam, Malolos','000001287','Roberto Cruz','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Santo Rosario (Pob.), Malolos','0000124','Maria Dela Cruz','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Santo Rosario (Pob.), Malolos','2000006400','Jose Garcia','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Kapitangan, Paombong','00022565','Carmen Reyes','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Meyto, Calumpit','09359829530','Fernando Lopez','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Santor, Malolos','10092017','Lourdes Torres','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Bulac, Santa Maria','10132017','Eduardo Ramos','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Caingin, Bocaue','2000001297','Gloria Hernandez','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Panasahan, Malolos','2000001383','Rodrigo Flores','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Caniogan, Calumpit','2000001419','Teresita Gutierrez','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('','0033','Andres Aquino','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('','00522','Consolacion Bautista','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('','005484','Domingo Villanueva','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('','2','Edna Castillo','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('','20000000939','Felix Morales','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('','0920-5494451','Glenda Mendoza','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('','032356','Hermogenes Pascual','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('','03264','Imelda Soriano','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('','03332','Juanito Gonzales','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('','09067725214','Katrina Perez','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('','092717','Leonardo Ramirez','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Sumapang Matanda, Malolos','N/A','Maryrose Navarro','Part-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Canalato, Malolos','09171234567','Nestor Aguilar','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Pao, San Jose, Tarlac','09281234567','Ofelia Domingo','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Pinagbakahan, Malolos','09391234567','Pablo Estrada','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Santo Cristo, Malolos','09451234567','Quirino Francisco','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Abulalas, Hagonoy','09561234567','Remedios Halili','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Santo Cristo, Malolos','09671234567','Salvador Ibarra','Full-Time');
INSERT INTO `agents` (`addr`,`contact`,`name`,`type`) VALUES ('Pipiton, Bulacan','09781234567','Trinidad Javier','Full-Time');
# TABLE addresses 30 rows
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Lugam, City of Malolos (Capital), Bulacan','A2015rW853');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Santo Rosario (Pob.), City of Malolos (Capital), Bulacan','A2015rW902');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Kapitangan, Paombong, Bulacan','A2015rW919');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Meyto, Calumpit, Bulacan','A2015rW195');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Santor, City of Malolos (Capital), Bulacan','A2015rW161');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Bulac, Santa Maria, Bulacan','A2015rW173');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Caingin, Bocaue, Bulacan','A2015rW461');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Panasahan, City of Malolos (Capital), Bulacan','A2015rW466');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Caniogan, Calumpit, Bulacan','A2015rW473');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Pio Cruzcosa, Calumpit, Bulacan','A2015rW572');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Sumapang Matanda, City of Malolos (Capital), Bulacan','A2015rW577');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Canalato, City of Malolos (Capital), Bulacan','A2015rW644');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Pao, San Jose, Tarlac','A2015rW650');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Pinagbakahan, City of Malolos (Capital), Bulacan','A2015rW680');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Santo Cristo, City of Malolos (Capital), Bulacan','A2015rW733');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Abulalas, Hagonoy, Bulacan','A2015rW780');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Santo Cristo, City of Malolos (Capital), Bulacan','A2015rW788');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Pipiton, Bulacan, Bulacan','A2015rW793');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Pinalogdan, Paombong, Bulacan','A2015rW842');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Pinagbakahan, City of Malolos (Capital), Bulacan','A2015rW848');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Kapitangan, Paombong, Bulacan','A2015rW887');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('San Miguel, Calumpit, Bulacan','A2015rX014');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Look 2nd, City of Malolos (Capital), Bulacan','A2015rX028');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Mojon, City of Malolos (Capital), Bulacan','A2015rX041');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Matimbo, City of Malolos (Capital), Bulacan','A2015rX122');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Mabolo, City of Malolos (Capital), Bulacan','A2015rX273');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Anilao, City of Malolos (Capital), Bulacan','A2015rX311');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Babatnin, City of Malolos (Capital), Bulacan','A2015rX405');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Balite, City of Malolos (Capital), Bulacan','A2015rX518');
INSERT INTO `addresses` (`addr`,`code`) VALUES ('Bulacnin, City of Malolos (Capital), Bulacan','A2015rX620');
# TABLE lookups 30 rows
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',1,'ΓÇö');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',2,'_');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',3,'1');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',4,'A');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',5,'A.');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',6,'Aaron');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',7,'ABADAM');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',8,'Abadecio');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',9,'Abalgar');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',10,'Aballe');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',11,'Abalos');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',12,'Abaloyan');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',13,'Abanog');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',14,'Aba├▒o');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',15,'Abdula');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',16,'Abejera');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',17,'Abejo');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',18,'Abelardo');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',19,'Abella');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',20,'Abellera');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',21,'Aberte');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',22,'Abiday');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',23,'Abillon');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',24,'Abino');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',25,'Abique');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',26,'Abisamis');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',27,'Ablang');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',28,'Ablaza');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',29,'Abner');
INSERT INTO `lookups` (`code`,`order`,`word`) VALUES ('',30,'Abolencia');
